Update CONTRIBUTING.md
GenomicsStandardsConsortium/mixs pull request #617
Opened 2023-10-17 16:27 UTC by pbuttigieg

Started the extension of the CONTRIBUTING.Md doc - more content should be added so devs know what and how to edit to maintain and extend MIxS. 

Closes #615

2023-10-17 16:29 UTC, pbuttigieg commented
@turbomam @sujaypatil96 - this PR targets main.

Is that right or is there a branch to stage the release?

2023-10-19 00:54 UTC, cmungall approved these changes

2023-10-19 13:08 UTC, turbomam approved these changes
Thanks for starting this, @pbuttigieg. This can be expanded upon in the future.

2023-10-19 13:10 UTC, turbomam commented
@pbuttigieg: there's a merge conflict. Do you prefer for the issues and pulls links to appear before or after your new text about modifying miixs.yaml?

2023-11-06 18:14 UTC, turbomam commented
I resolved the merge conflict by placing @pbuttigieg's new content after the links about issues and pull requests

2023-12-29 00:42 UTC, ramonawalls commented
@pbuttigieg I think I have covered this content in https://github.com/GenomicsStandardsConsortium/mixs/tree/606-mixs-editing-workflow-and-policy. May I close this PR without merging?

2024-04-05 21:38 UTC, cmungall commented
@ramonawalls
> I think I havw covered or will cover this content in https://github.com/GenomicsStandardsConsortium/mixs/tree/606-mixs-editing-workflow-and-policy. May I close this PR without merging?

This linked to a long-running branch with many changes from multiple people. I made a PR for this to make it easier to see the changes:

https://github.com/GenomicsStandardsConsortium/mixs/pull/617/files

However, it looks like @pbuttigieg's PR has independent and useful contributions on how to find the yaml file to edit, etc, so I would like to merge this.

Also, can I make a plea for

- smaller, incremental PRs
- breaking larger pieces of work into smaller
- no long running branches
- always having a PR for each branch to make it more visible
- faster decisions and merges on smaller PRs

Otherwise things get out of sync. This PR is from October. The linked PR is from 5 months ago. All of the good work in these PRs is not yet visible on the site. I know it's hard as we are volunteering time but some simple changes in practice can help us make use of our time more effectively

2024-07-18 00:02 UTC, mslarae13 commented
Very old PR. Should we merge main and merge this? 
@turbomam @pbuttigieg

2024-07-18 00:08 UTC, pbuttigieg commented
@mslarae13 yes, but @turbomam to verify content is still current

2025-04-02 17:19 UTC, turbomam commented on CONTRIBUTING.md
> +[issues]: https://github.com/GenomicsStandardsConsortium/mixs-6-2-for-merge/issues/
```suggestion
[issues]: https://github.com/GenomicsStandardsConsortium/mixs-6-2-for-merge/issues/
[issues]: https://github.com/GenomicsStandardsConsortium/mixs/issues/
[pulls]: https://github.com/GenomicsStandardsConsortium/mixs/pulls/
```

GenomicsStandardsConsortium/mixs-6-2-for-merge was a development/transitory repo. We shouldn't link to it in this document.

2025-04-02 17:21 UTC, turbomam commented on CONTRIBUTING.md
> +[pulls]: https://github.com/GenomicsStandardsConsortium/mixs-6-2-for-merge/pulls/
```suggestion
[issues]: https://github.com/GenomicsStandardsConsortium/mixs/issues/
[pulls]: https://github.com/GenomicsStandardsConsortium/mixs/pulls/
```

GenomicsStandardsConsortium/mixs-6-2-for-merge was a development/transitory repo. We shouldn't link to it in this document.

2025-04-02 17:22 UTC, turbomam requested changes
Thanks, this is a good addition. I'm just suggesting keeping the original links to 

GenomicsStandardsConsortium/mixs

2025-05-30 13:08 UTC, merged