Add schema description to `src/mixs/schema/mixs.yaml`
GenomicsStandardsConsortium/mixs pull request #788
Opened 2024-04-03 23:04 UTC by sujaypatil96

Notes about the text for the description from Pier can be found here: https://docs.google.com/document/d/1HCmKUGFBm4P8dPCXqL_jOuXe02SF5jQ8hPnTlhanm1Q/edit?usp=sharing

2024-04-03 23:05 UTC, sujaypatil96 commented
Feel free to suggest changes to the description.

2024-04-08 17:57 UTC, sujaypatil96 commented
@pbuttigieg wanted to get your thoughts on this description for the schema. Do let me know if you want me to modify it somehow.

2024-04-10 08:12 UTC, pbuttigieg requested changes
There should be no line breaks or Md formatting in the yaml description field. 

I also made the language a little more precise.

I removed the link to the file itself (that was a self-reference right?) - that should be in a dedicated field

2024-04-10 08:12 UTC, pbuttigieg commented on src/mixs/schema/mixs.yaml
> +  The MIxS (Minimum Information about any (x) Sequence) standard is specified in a YAML file
```suggestion
  This file contains a YAML-formatted specification of the Minimum Information about any (x) Sequence (MIxS) standard, generated using LinkML (https://linkml.io/linkml/). This file is released by the Genomic Standards Consortium (GSC; https://www.gensc.org/) for use by anyone handling data or information about biological sequences. This file is also used as an authoritative 'source of truth' to generate downstream GSC artifacts, available here: https://github.com/GenomicsStandardsConsortium/mixs/tree/main/project
```

2024-04-10 08:12 UTC, pbuttigieg commented on src/mixs/schema/mixs.yaml
> +  [here](https://github.com/GenomicsStandardsConsortium/mixs/tree/main/project).
```suggestion
```

2024-04-10 17:10 UTC, pbuttigieg approved these changes
Green light from me

2024-04-10 17:23 UTC, merged